import type { AppItem } from './types';

/**
 * Seed catalogue of popular APK / MOD apps.
 * Used for offline fallback and initial render.
 */
export const APPS: AppItem[] = [
  {
    uid: 'app-minecraft',
    name: 'Minecraft',
    version: '1.21.80.3',
    size: '690 MB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
    description:
      'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode.',
    developer: 'Mojang Studios',
    updated: 'Jul 28, 2026',
    downloads: '200M+',
    rating: 4.5,
    androidReq: '8.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Immortality',
    genre: 'Sandbox',
    genres: ['Sandbox', 'Survival', 'Adventure'],
    trending: true,
    editorChoice: true
  },
  {
    uid: 'app-gta-san',
    name: 'GTA: San Andreas',
    version: '2.12',
    size: '2.1 GB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
    description:
      'Five years ago, Carl Johnson escaped from the pressures of life in Los Santos, San Andreas. Now, it\'s the early 90s and CJ has to go home.',
    developer: 'Rockstar Games',
    updated: 'Jul 20, 2026',
    downloads: '50M+',
    rating: 4.3,
    androidReq: '7.0+',
    tags: ['APK', 'MOD', 'OBB'],
    modFeature: 'Unlimited Money',
    genre: 'Action',
    genres: ['Action', 'Adventure', 'Open World'],
    trending: true,
    editorChoice: true
  },
  {
    uid: 'app-yt-music',
    name: 'YouTube Music',
    version: '9.25.50',
    size: '78 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
    description:
      'YouTube Music is a new music app that allows you to easily find what you\'re looking for and discover new music. Get playlists and recommendations.',
    developer: 'Google LLC',
    updated: 'Jul 29, 2026',
    downloads: '5B+',
    rating: 4.2,
    androidReq: '8.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Premium Unlocked',
    genre: 'Music',
    genres: ['Music', 'Entertainment'],
    trending: true,
    editorChoice: false
  },
  {
    uid: 'app-inshot',
    name: 'InShot',
    version: '2.105.1',
    size: '67 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
    description:
      'InShot - Best FREE HD video editor and video maker with all features, trim & cut video/movie, add music, text, stickers and glitch effects.',
    developer: 'InShot Inc.',
    updated: 'Jul 27, 2026',
    downloads: '500M+',
    rating: 4.6,
    androidReq: '7.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Pro Unlocked',
    genre: 'Video Players',
    genres: ['Video Players', 'Editing', 'Photography'],
    trending: false,
    editorChoice: true
  },
  {
    uid: 'app-minecraft-pe',
    name: 'Minecraft PE',
    version: '1.21.80',
    size: '715 MB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
    description:
      'The Pocket Edition of Minecraft lets you build, explore and survive on the go. Multiplayer support with up to 10 friends across platforms.',
    developer: 'Mojang Studios',
    updated: 'Jul 26, 2026',
    downloads: '100M+',
    rating: 4.4,
    androidReq: '8.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'God Mode',
    genre: 'Sandbox',
    genres: ['Sandbox', 'Survival'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-spotify',
    name: 'Spotify',
    version: '9.0.48',
    size: '95 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/1926/140799.jpg',
    description:
      'With Spotify, you can listen to millions of songs and podcasts for free. Listen to the songs and podcasts you love and find music from all over the world.',
    developer: 'Spotify AB',
    updated: 'Jul 30, 2026',
    downloads: '1B+',
    rating: 4.4,
    androidReq: '7.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Premium Unlocked',
    genre: 'Music',
    genres: ['Music', 'Entertainment'],
    trending: true,
    editorChoice: true
  },
  {
    uid: 'app-stumble-guys',
    name: 'Stumble Guys',
    version: '0.78.5',
    size: '258 MB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/6/73245.jpg',
    description:
      'Stumble Guys is a massively multiplayer party knockout game with up to 32 players online. Run, stumble and fall against your opponents.',
    developer: 'Scopely',
    updated: 'Jul 25, 2026',
    downloads: '200M+',
    rating: 4.1,
    androidReq: '5.1+',
    tags: ['APK', 'MOD'],
    modFeature: 'Unlimited Gems',
    genre: 'Party',
    genres: ['Party', 'Multiplayer', 'Casual'],
    trending: true,
    editorChoice: false
  },
  {
    uid: 'app-canon',
    name: 'CapCut',
    version: '14.2.0',
    size: '235 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg',
    description:
      'CapCut is a free all-in-one video editing app that helps you create incredible videos. It\'s packed with advanced features trusted by millions.',
    developer: 'Bytedance',
    updated: 'Jul 31, 2026',
    downloads: '1B+',
    rating: 4.3,
    androidReq: '5.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Pro Unlocked',
    genre: 'Video Players',
    genres: ['Video Players', 'Editing', 'Photography'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-dr-driving',
    name: 'Dr. Driving',
    version: '1.70',
    size: '12 MB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/1935/127974.jpg',
    description:
      'Dr. Driving drives you crazy! Burn up the street with the fastest and most visually stunning driving game with various missions.',
    developer: 'SUD Inc.',
    updated: 'Jul 15, 2026',
    downloads: '500M+',
    rating: 4.0,
    androidReq: '4.4+',
    tags: ['APK', 'MOD'],
    modFeature: 'Unlimited Gold',
    genre: 'Racing',
    genres: ['Racing', 'Driving', 'Simulation'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-wa-business',
    name: 'WhatsApp Business',
    version: '2.26.16',
    size: '65 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/12/76049.jpg',
    description:
      'WhatsApp Business is a free-to-download app built for small business owners. Connect with customers, showcase products and grow your business.',
    developer: 'Meta Platforms',
    updated: 'Jul 29, 2026',
    downloads: '5B+',
    rating: 4.1,
    androidReq: '5.0+',
    tags: ['APK'],
    genre: 'Communication',
    genres: ['Communication', 'Social'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-nfs',
    name: 'Need for Speed No Limits',
    version: '8.2.0',
    size: '1.4 GB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/1806/126216.jpg',
    description:
      'Claim the crown and rule the underground street racing scene. Build your dream ride with an unbelievable range of cars and customizations.',
    developer: 'Electronic Arts',
    updated: 'Jul 22, 2026',
    downloads: '100M+',
    rating: 4.2,
    androidReq: '4.4+',
    tags: ['APK', 'MOD', 'OBB'],
    modFeature: 'Unlimited Money',
    genre: 'Racing',
    genres: ['Racing', 'Action', 'Cars'],
    trending: true,
    editorChoice: false
  },
  {
    uid: 'app-netflix',
    name: 'Netflix',
    version: '9.11.0',
    size: '88 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/3/40451.jpg',
    description:
      'Looking for the most talked-about TV shows and movies from around the world? They\'re all on Netflix. Watch anywhere, cancel anytime.',
    developer: 'Netflix Inc.',
    updated: 'Jul 30, 2026',
    downloads: '1B+',
    rating: 4.5,
    androidReq: '7.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Premium Unlocked',
    genre: 'Entertainment',
    genres: ['Entertainment', 'Video Players'],
    trending: true,
    editorChoice: true
  },
  {
    uid: 'app-brawl',
    name: 'Brawl Stars',
    version: '59.197',
    size: '630 MB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/1223/96541.jpg',
    description:
      'Fast-paced 3v3 multiplayer and battle royale made for mobile! Play with friends or solo across a variety of game modes in under three minutes.',
    developer: 'Supercell',
    updated: 'Jul 28, 2026',
    downloads: '200M+',
    rating: 4.3,
    androidReq: '7.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Unlimited Gems',
    genre: 'Action',
    genres: ['Action', 'Multiplayer', 'Shooter'],
    trending: true,
    editorChoice: false
  },
  {
    uid: 'app-kinemaster',
    name: 'KineMaster',
    version: '7.5.6',
    size: '105 MB',
    category: 'app',
    icon: 'https://cdn.myanimelist.net/images/anime/9/9453.jpg',
    description:
      'KineMaster is the best video editor for Android. Edit videos with powerful tools, music, effects and stickers. Share on YouTube, TikTok and more.',
    developer: 'KineMaster Corp.',
    updated: 'Jul 24, 2026',
    downloads: '500M+',
    rating: 4.2,
    androidReq: '8.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'No Watermark',
    genre: 'Video Players',
    genres: ['Video Players', 'Editing'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-pubg',
    name: 'PUBG Mobile',
    version: '3.7.0',
    size: '1.1 GB',
    category: 'game',
    icon: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg',
    description:
      'PUBG MOBILE delivers the most intense free-to-play multiplayer action on mobile. Drop in, gear up, and compete. Survive epic 100-player battles.',
    developer: 'Krafton',
    updated: 'Jul 31, 2026',
    downloads: '1B+',
    rating: 4.0,
    androidReq: '6.0+',
    tags: ['APK', 'MOD', 'OBB'],
    modFeature: 'Anti-Ban',
    genre: 'Shooter',
    genres: ['Shooter', 'Action', 'Battle Royale'],
    trending: true,
    editorChoice: true
  },
  {
    uid: 'app-torrent',
    name: 'BitTorrent',
    version: '8.2.2',
    size: '24 MB',
    category: 'tool',
    icon: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg',
    description:
      'Find, download and play torrents anywhere you go. The original torrent app for Android with no speed limits and no download size limits.',
    developer: 'Rainberry Inc.',
    updated: 'Jul 18, 2026',
    downloads: '100M+',
    rating: 4.1,
    androidReq: '5.0+',
    tags: ['APK', 'PRO'],
    modFeature: 'Pro Unlocked',
    genre: 'Tools',
    genres: ['Tools', 'Download'],
    trending: false,
    editorChoice: false
  },
  {
    uid: 'app-nordvpn',
    name: 'NordVPN',
    version: '7.38',
    size: '58 MB',
    category: 'tool',
    icon: 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg',
    description:
      'NordVPN is a VPN app for safe and private internet access. Protect your online activities with military-grade encryption. 60+ countries.',
    developer: 'Nord Security',
    updated: 'Jul 27, 2026',
    downloads: '100M+',
    rating: 4.4,
    androidReq: '7.0+',
    tags: ['APK', 'MOD'],
    modFeature: 'Premium Unlocked',
    genre: 'Tools',
    genres: ['Tools', 'Security', 'VPN'],
    trending: false,
    editorChoice: true
  }
];
